### ISSUE TITLE
does not support [appendTo]="'body'" :/

### ISSUE THREAD

**Issue by ghost** [Saeed-Pooyanfar/ng-persian-datepicker#11]
using this component inside table row causes to extend row height ! its better to set [appendTo]="'body'" like ng2 select link : https://github.com/ng-select/ng-select/issues/240#issuecomment-380382324

**Comment by keivansahebdelfard** [comment]
> using this component inside table row causes to extend row height ! its better to set [appendTo]="'body'" like ng2 select link : [ng-select/ng-select#240 (comment)](https://github.com/ng-select/ng-select/issues/240#issuecomment-380382324)

try this : 
`<:host >>> ng-persian-datepicker {
  position: relative;
  display: block;
}

:host >>> ng-persian-datepicker > .datepicker-outer-container {
  position: absolute;
  left: 0;
  right: 0;
  margin: 0 auto;
  width: 100%;
  margin-top: 2px;
  border-radius: 5px;
}>`

**Comment by Saeed-Pooyanfar** [comment]
Hi,
You can also try `[uiAutoPosition]="true"`

**Comment by arashkey** [comment]
Another way
```
<ng-persian-datepicker 
[ngStyle]="{'position': 'absolute', 'width': '250px', 'z-index':'1000'}"
```

**Comment by Saeed-Pooyanfar** [comment]
> > Hi, You can also try `[uiAutoPosition]="true"`
> 
> It 's not working correctly some times fly things to the wrong place

Yeah,
[I just remove it](https://github.com/Saeed-Pooyanfar/ng-persian-datepicker/commit/7c54a12aa7af793523b79d8d886315baaa82817c)
User must handle datepicker position manually ...
