### ISSUE TITLE
Gregorian value

### ISSUE THREAD

**Issue by mehdizz** [Saeed-Pooyanfar/ng-persian-datepicker#12]
Hi 
this [dateIsGregorian]="true" does not work?!
and this [dateValue]="number"  does not work?!

https://stackblitz.com/edit/angular-ivy-xemyac?file=src%2Fapp%2Fapp.component.html

**Comment by Saeed-Pooyanfar** [comment]
Hi,
The `[dateIsGregorian]` boolean option simply means `[dateValue]` you passed to `<ng-persian-datepicker />` is gregorian or not
`ng-persian-datepicker` isn't for choosing gregorian date
