### ISSUE TITLE
how to use dateMin and dateMax with 2 ng-persian-datepicker ?

### ISSUE THREAD

**Issue by fadakar** [Saeed-Pooyanfar/ng-persian-datepicker#14]
Hi, I have 2 ng-persian-datepicker in page and want to connect them with dateMin and dateMax 
please help me

**Comment by Saeed-Pooyanfar** [comment]
Hi, please describe what do you mean by connecting with dateMin and dateMax ?!
You can pass dateMin to first one and dateMax to second :)
