### ISSUE TITLE
قابل ویرایش نبودن مقدار تاریخ بصورت دستی

### ISSUE THREAD

**Issue by RezaMakvandi** [Saeed-Pooyanfar/ng-persian-datepicker#31]
چطور میشه مقدار تاریخ رو بصورت دستی تغییر بدم؟ چون بصورت پیش فرض قابل ویرایش نیست

**Comment by Saeed-Pooyanfar** [comment]
You can't !
Maybe I'll add this feature in next versions ...

**Comment by RezaMakvandi** [comment]
I'm waiting for it. Thank you

**Comment by arashkey** [comment]
به سختی ولی انجام شد
`
.html
 <ng-persian-datepicker   #DatePicker

.ts

export class Test
{
  @ViewChild('DatePicker') DatePicker;
doChangeDateTime(){
      this.DatePicker.dateValue = model.serverDate.replace('T', ' ');
      this.DatePicker.setSelectedDate();
      this.DatePicker.setViewDate();
      this.DatePicker.setTime();
      this.DatePicker.seTimeText();
      this.DatePicker.setInputValue();
      this.DatePicker.lockInputValue();
      this.DatePicker.setShowOnInputFocus();
}
}
`
مهندس خوب یک فانکشن بزار براش برای اینکه بشه تاریخ رو واسش ثبت کرد

**Comment by Saeed-Pooyanfar** [comment]
@RezaMakvandi 
Check v3.0.0
Thanks!

**Comment by RezaMakvandi** [comment]
Great job, thanks alot.
The best angular persian date picker!
