### ISSUE TITLE
[uiHideAfterSelectDate]="true" does not work

### ISSUE THREAD

**Issue by hoda02** [Saeed-Pooyanfar/ng-persian-datepicker#32]
Hi, 
I set [uiHideAfterSelectDate]="true" but does not work
please guide me
Thank you...

**Comment by Saeed-Pooyanfar** [comment]
Hi,
As you can see in online demo it's working correctly
Maybe after selecting date you have a focus event for the input
(By default it opens when you focus on the input)

**Comment by hoda02** [comment]
Thank for your fast reply,
yes, My problem is using the mat-input

**Comment by Saeed-Pooyanfar** [comment]
Please provide a full example with https://stackblitz.com/

**Comment by Saeed-Pooyanfar** [comment]
@hoda02 please check v4.0.0
Thanks!
