### ISSUE TITLE
dont set value in input 

### ISSUE THREAD

**Issue by behroozbc** [Saeed-Pooyanfar/ng-persian-datepicker#4]
hi 
thanks for your component 
i test it i think have bug 
https://stackblitz.com/edit/angular-ivy-aepwjb
please see this and help me

**Comment by Saeed-Pooyanfar** [comment]
Hi, thanks for the report :)
Please checkout new version: 2.3.2

**Comment by behroozbc** [comment]
thanks 
i check in stackblitz 
worked
