### ISSUE TITLE
dateOnSelect called twice when set dateformat

### ISSUE THREAD

**Issue by ehsan-kargar** [Saeed-Pooyanfar/ng-persian-datepicker#55]
When dateFormat is default dateOnSelect called once but when set dateFormat dateOnSelect called twice 

https://stackblitz.com/edit/angular-ivy-xgpj3h?file=src%2Fapp%2Fapp.component.html

**Comment by Saeed-Pooyanfar** [comment]
Thanks for the report.
It should be fixed in next version: `v4.1.1`

**Comment by Saeed-Pooyanfar** [comment]
@ehsan-kargar I just released v4.1.1, try it !

**Comment by ehsan-kargar** [comment]
> @ehsan-kargar I just released v4.1.1, try it !

Thank you for your quick response
