### ISSUE TITLE
Set year view as initial view

### ISSUE THREAD

**Issue by ehsan-kargar** [Saeed-Pooyanfar/ng-persian-datepicker#59]
I want to show the year-view on the first date picker view. How to set the year-view as the initial View?

**Comment by Saeed-Pooyanfar** [comment]
Please read `README.md` :

> Complete config reference:
> 
> | Key                   | Type    | Description                                                                                                          | Example                                         |
> |----------------------|---------|----------------------------------------------------------------------------------------------------------|-----------------------------------------------|
> | uiInitViewMode | string | Initial view mode ('year', 'month', 'day'). default: 'day'                                           | 'year'                                               |
