### ISSUE TITLE
Using Angular CDK overlay 

### ISSUE THREAD

**Issue by newshahn** [Saeed-Pooyanfar/ng-persian-datepicker#6]
Hi Saeed,
First of all, thank you for this awesome library. Don't know what i would have done without it.
I was wondering if you could maybe use Angular overlay to make this datepicker open on top of other elements instead of just pushing them down.
Like the behavior that Angular material datepicker currently has.
It just opens on top of other elements on the page.
Thank you so much in advance.
Keep up the good work :)

**Comment by Saeed-Pooyanfar** [comment]
Hi, Sorry for late reply, i'm very busy nowadays ..!
Maybe you can implement it manually? :
https://material.angular.io/cdk/overlay/overview
