### ISSUE TITLE
dateMin and dateMax not affect the date picker immediately when their values change

### ISSUE THREAD

**Issue by FullStackDeveloperrrr** [Saeed-Pooyanfar/ng-persian-datepicker#63]
Hi Saeed
I've used two variables for dateMin and dateMax for setting the min and max date like below :
`<ng-persian-datepicker
  [dateMin] = "minDate"
  [dateMax] = "maxDate"
...
`
These work fine once I initial minDate and maxDate in my component. For some reason, the value of these two variables may be changed after initialization by some actions like clicking on a button! In these cases, when I open the date picker, the new min and max date do not affect on date picker and the old values of min and max date are still affecting the date picker. This will be fixed if I change the month or select an active date.
Actually, I need something like refreshing the date picker whenever the values of minDate and maxDate change. How to do that?
Thanks in advance

**Comment by Saeed-Pooyanfar** [comment]
You can use this temporary solution until next version:
```html
<ng-container *ngIf="condition">
  <ng-persian-datepicker ...>
    ...
  </ng-persian-datepicker>
</ng-container>
```
```typescript
refreshDatepicker(): void {
  this.condition = false;
  setTimeout(() => this.condition = true, 10);
}
```

**Comment by FullStackDeveloperrrr** [comment]
Your solution works fine. Thank you so much for your help

**Comment by FullStackDeveloperrrr** [comment]
It works fine. Thank you, Saeed.
I will close the topic
