### ISSUE TITLE
Overlays with Angular's CDK

### ISSUE THREAD

**Issue by saeidi-dev** [Saeed-Pooyanfar/ng-persian-datepicker#65]
Hello
It may be difficult to display your datepicker in some places. You must implement the datepicker-outer-container div with @angular / cdk / overlay. This will place the date display at the bottom of the body tag.

Thanks

sample code:

```
 constructor(private overlay: Overlay) { }

  open() {
    // Returns an OverlayRef which is a PortalHost
    const overlayRef = this.overlay.create();

    // Create ComponentPortal that can be attached to a PortalHost
    const filePreviewPortal = new ComponentPortal(FilePreviewOverlayComponent);

    // Attach ComponentPortal to PortalHost
    overlayRef.attach(filePreviewPortal);
  }
```

**Comment by Saeed-Pooyanfar** [comment]
@saeidi-dev Sorry, i don't want to increase my lib dependencies, however, users are free to install whatever they want ...

**Comment by saeidi-dev** [comment]
Your datepicker is not working properly in display mode. For example, I used it in ag-grid in the Floating Filter Component section.

url:
https://www.ag-grid.com/javascript-data-grid/component-date/
https://ag-grid.com/angular-data-grid/component-floating-filter/

**Comment by saeidi-dev** [comment]
> @saeidi-dev Sorry, i don't want to increase my lib dependencies, however, users are free to install whatever they want ...

Your datepicker is not working properly in display mode. For example, I used it in ag-grid in the Floating Filter Component section

url:
https://www.ag-grid.com/javascript-data-grid/component-date/
https://ag-grid.com/angular-data-grid/component-floating-filter/
