### ISSUE TITLE
Use 'YYYY' format in version 6.1.2

### ISSUE THREAD

**Issue by ehsan-kargar** [Saeed-Pooyanfar/ng-persian-datepicker#80]
In version 4.1.2 , we were allowed to use 'YYYY' format, is this not possible in version 6.1.2 ?

The following code works in version 4.1.2, but it has problems in version 6.1.2 !

```
<ng-persian-datepicker [dateInitValue]="false" [uiTheme]="'default'"
                [uiYearView]="isYearView" [uiMonthView]="true" [uiHideOnOutsideClick]="true" [uiTodayBtnEnable]="false"
                [timeEnable]="false" [timeMeridian]="false" [dateFormat]="condition ? 'YYYY' : 'YYYY/MM/DD'"
                [uiInitViewMode]="datePickerInitialViewMode" (dateOnSelect)="birthDateOnSelect($event)">
                <div>
                  <input type="text" formControlName="birthDate" />
                </div>
</ng-persian-datepicker>
```

**Comment by Saeed-Pooyanfar** [comment]
Currently if `[dateFormat]` change, the next date selection by user will appear with new format  
(I'm not sure about this, but you can probably update the FormControl value on your condition change to the new format)
