### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Rezar00** [Saeed-Pooyanfar/ng-persian-datepicker#9]
Hi, 
Ive used this component, but when i put it into a mat-form-field and try to open it, it resize mat input height!!

how could i open it over my input?

**Comment by Saeed-Pooyanfar** [comment]
Hi, please provide a sample on https://stackblitz.com

**Comment by hamedsbt** [comment]
> Hi,
> Ive used this component, but when i put it into a mat-form-field and try to open it, it resize mat input height!!
> 
> how could i open it over my input?

Also uiHideAfterSelectDate does not works properly!
